# Site Settings
title: My Profile
url: 'https://rajputonsecurity.com'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Priyanka Sapkal
tagline: Graduate Student
pic: profile_pic.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Hello! I'm Priyanka Sapkal, a graduate student in the Computer Engineering department at NYU. I'm always looking for 
opportunities to collaborate and work in the field of Machine Learning. I'm motivated to solve real world problems by using Machine 
Learning and I truely believe that in the future, Machine Learning will be encorporated in major modern applications.<br />
Feel free to contact me if you would want to have a discussion with me. Click 
<a href="https://github.com/priyanka-sapkal/online-cv/raw/master/assets/resume/priyanka_resume.pdf" download="Priyanka_Sapkal_Resume">here</a> to download a pdf version of my resume."
awards: True

#sidebar links
email: pas571@nyu.edu
#phone: 012 345 6789
#website: rajputonsecurity.com #do not add http://
linkedin: priyankasapkal
github: priyanka-sapkal
#facebook: priyanka.sapkal.378
#twitter: '@starlordphr'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
